---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  BronzeSourceTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: data_pipeline/bronze/source/table/package.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          API_KEY: 65c2bf3138f0b29ee4cec4fef2261a29
          BRONZE_BUCKET: uffic-bronze-eucentral1-473178649040-dev
      Architectures:
        - x86_64
      Layers:
        - !Ref PythonDependenciesLayer

  PythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: python-dependencies
      Description: Dependencies for the BronzeSourceTableFunction
      ContentUri: data_pipeline/bronze/source/table/python.zip
      CompatibleRuntimes:
        - python3.8
